services:
  runestone:
    image: postgres:14
    container_name: runestone       
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SkillSync
    ports:
      - "5433:5432"                  
    volumes:
      - runestone-data:/var/lib/postgresql/data
    networks:
      - runestone-net

  skill-sync-api:
    build: .
    container_name: skill-sync-api
    env_file:
      - .env
    environment:
    
      DATABASE_URL: {DATABASE_URL_DOCKER}
    depends_on:
      - runestone                  
    ports:
      - "8000:8000"
    networks:
      - runestone-net

networks:
  runestone-net:
    driver: bridge
  

volumes:
  runestone-data: