services:

  skill-sync-api:
    build: .
    container_name: skill-sync-api
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}           
    ports:
      - "8000:8000"
    networks:
      - runestone-net
networks:
  runestone-net:
    external: true
    name : runestone-net
  